---
name: SlapperRotation
version: 1.0.2
main: ReinfyTeam\SlapBack\Main
api: 5.0.0
src-namespace-prefix: ReinfyTeam\SlapBack
depend: Slapper
author: ReinfyTeam
description: Slappers now hit back at you!
...
