<?php

namespace xqwtxon\SlapBackV2;

interface SlapInfo {
    /**
     * NOTE FOR DEVELOPERS:
     * CHANGING THIS COULD BREAK THIS PLUGIN!
     * 
     * SUBMITTING PULL REQUEST TO CHANGE THIS PLUGIN COMPATIBLE VERSION WILL AUTOMATICALLY CLOSED!
     * YOU ARE WASTING TIME FOR MODIFYING THIS!
     * 
     * THIS FILE WAS AUTO-GENERATED BY PLUGIN!
    **/
    const PLUGIN_NAME = "SlapBackV2";
    const BRANCH = "main";
    const PLUGIN_DESCRIPTION = "Slappers now hit back at you!";
    const MAIN = "Main";
    const CONFIG_VERSION = "1.0.0";
    const POCKETMINE_VERSION = "4.3.2";
    const PROTOCOL_VERSION = 503;
    const PLUGIN_VERSION = "2.0.1";
    const VERSION = "v2.0.1";
    const IS_DEVELOPMENT_BUILD = false;
}
